# Generated by Django 3.1.2 on 2020-10-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentField',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False, verbose_name='primary key')),
                ('pub_date', models.DateTimeField(verbose_name='Date Field')),
                ('text_content', models.TextField(max_length=300, verbose_name='Text Field')),
                ('author', models.CharField(max_length=26, verbose_name='Author')),
            ],
        ),
    ]
