# Generated by Django 3.1.2 on 2020-10-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentfield',
            name='author_id',
            field=models.IntegerField(default=-1, verbose_name='author_id'),
        ),
    ]
