# Generated by Django 3.1.2 on 2020-10-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_commentfield_author_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False, verbose_name='pk')),
                ('pub_date', models.DateTimeField(verbose_name='Published Date')),
                ('title', models.TextField(verbose_name='Title')),
                ('img_link', models.TextField(verbose_name='img link')),
                ('text_content', models.TextField(verbose_name='text_content')),
                ('author', models.CharField(max_length=30, verbose_name='Author')),
                ('author_id', models.IntegerField(verbose_name='Author id')),
            ],
        ),
    ]
