# Generated by Django 3.1.2 on 2020-11-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='img_height',
            field=models.IntegerField(default=200, verbose_name='image heigth'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='img_width',
            field=models.IntegerField(default=300, verbose_name='image widht'),
        ),
    ]
