# Generated by Django 3.1.2 on 2020-11-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='secret_email_auth_token',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_id',
            field=models.IntegerField(default=-1, verbose_name='ID of user linked to this userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(default=0, verbose_name='email authenticated or not'),
        ),
    ]
