# Generated by Django 3.1.2 on 2020-11-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20201109_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_send',
            field=models.BooleanField(default=False, verbose_name='email sent'),
        ),
    ]
