# Generated by Django 3.1.2 on 2020-11-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_userprofile_email_send'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False, verbose_name='pk')),
                ('author', models.CharField(max_length=26, verbose_name='author username')),
                ('pub_date', models.DateTimeField(verbose_name='data of release')),
                ('img_link', models.CharField(max_length=150, verbose_name='link to image included')),
                ('github_link', models.CharField(max_length=160, verbose_name='link to github repo')),
                ('img_width', models.IntegerField(verbose_name='image_width')),
                ('img_height', models.IntegerField(verbose_name='image_height')),
                ('text_content', models.CharField(max_length=1500, verbose_name='project description')),
                ('author_id', models.IntegerField(verbose_name='Id of author')),
                ('title', models.CharField(max_length=200, verbose_name='Project title')),
            ],
        ),
    ]
